require 'faker'

puts "🌱 Seeding spices..."

10.times do
    Customer.create(name: Faker::Name.name, phone: rand(1111111111..9999999999), address: Faker::Address.full_address, email: Faker::Internet.email, password: Faker::Internet.password)
end

Guitar.create(name: "Guild OM-240CE Orchestra Acoustic-Electric Guitar", description: "This mid-sized orchestra-shaped acoustic is equally suited for strumming and fingerpicking, and produces a sweet, balanced tone. The perfect choice for the versatile musician, the OM-240CE features a solid Sitka spruce top, mahogany sides, arched mahogany back and an elegant cutaway for access to higher frets.", price: 529.00, image_url: "https://media.guitarcenter.com/is/image/MMGS7/L48602000003000-00-720x720.jpg")
Guitar.create(name: "Gibson J-45 Studio Rosewood Acoustic-Electric Guitar Antique Natural", description: "Turn heads with this unique Gibson J-45 Studio, hand-built using rosewood back and sides with a Sitka spruce top. The slim body depth allows for increased comfort underarm and the flatter fingerboard allows a finer playability. Finished with a Fishman Sonitone pickup for easy studio quality plug and play anywhere.", price: 2399.00, image_url: "https://media.guitarcenter.com/is/image/MMGS7/L73547000001000-00-720x720.jpg")
Guitar.create(name: "Recording King Dirty 30s 7 RDS-7 Dreadnought Acoustic Guitar Tobacco Sunburst", description: "Expanding the hugely popular Dirty 30s Series 7 line, the Series 7 dreadnought rounds out the line with deeper bass and expanded options. Featuring Recording King's super-clean Cross Lap bracing and top-quality materials, the Series 7 remains one of the best-sounding values available on the market. The spruce top is striking beneath the Tobacco Sunburst finish, cleanly marked by the ivory color body binding and bound soundhole. The parallelogram stencil fretboard markers are both a nod to history, and a design never before seen in this way.", price: 179.99, image_url: "https://media.guitarcenter.com/is/image/MMGS7/K46144000001000-00-720x720.jpg")
Guitar.create(name: "Peavey DW-2 Dreadnought Acoustic Guitar Natural", description: "The DW-2 Dreadnought from Peavey is designed for amazing sound, comfortable playability and value. Constructed with premium materials, the DW-2 features a solid spruce top, a mahogany body and a rosewood fretboard providing a sharp look and a smooth feel regardless of skill level. Additional features include a compensated saddle for optimal intonation, hard-carved bracing for balanced tone distribution and a dual action truss rod for enhanced longevity.", price: 199.99, image_url: "https://media.guitarcenter.com/is/image/MMGS7/L83338000001000-00-720x720.jpg")
Guitar.create(name: "Breedlove Discovery Concert Sitka Spruce-Mahogany Acoustic Guitar Bourbon Burst", description: "Mahogany acoustic guitars boast a versatile play style, which makes the Breedlove Discovery Concert ideal for a variety of play styles—from strumming and rhythm to fingerstyle play. The Concert body shape is constructed with a solid Sitka spruce top and mahogany back and sides for a clean, balanced and superb-sounding guitar with a warm midrange tone. The 1 11/16 inch radius neck and low action make it fun and easy to play for any skill level.", price: 329.99, image_url: "https://media.guitarcenter.com/is/image/MMGS7/L73305000001000-00-720x720.jpg")
Guitar.create(name: "Washburn HG26SCE-O Heritage Grand Auditorium Acoustic-Electric Guitar Natural", description: "The HG26SCE-O is a Grand Auditorium acoustic guitar with cutaway for superior upper fret access. It features a solid Western red cedar top with Cathedral Peak Scalloped-X bracing for sublime tone that improves with age, pau ferro back and sides, a mahogany neck with an ovangkol fingerboard and bridge, die-cast tuners with stylish ebonite buttons for quick, easy and accurate tuning, a Washburn tortoise pickguard and abalone rosette.", price: 579.00, image_url: "https://media.guitarcenter.com/is/image/MMGS7/L39511000001000-00-720x720.jpg")
Guitar.create(name: "Lag Guitars Tramontane T70ACE Auditorium Cutaway Acoustic-Electric Guitar Satin Natural", description: "Beyond the singular aesthetics of French craftsmanship that characterizes the Tramontane series, the T70 imposes itself in the world of the entry-level acoustic guitars with a solid spruce top that's rich and deep in tone. Sound quality, combined with a comfortable playing experience essential to the beginner, make it a great-value acoustic-electric guitar.", price: 549.99, image_url: "https://media.guitarcenter.com/is/image/MMGS7/L75758000001000-00-720x720.jpg")
Guitar.create(name: "Taylor 322 V-Class Grand Concert Acoustic Guitar Shaded Edge Burst", description: "Taylor's 300 Series has introduced countless players to the pleasures of the all-solid-wood acoustic experience; it's the entry point to Taylor's USA-made instrument line. Players who step up to a 300 Series instrument, like the 322 V-Class Grand Concert acoustic guitar, will be rewarded with a guitar-for-a-lifetime that will only sound better with age. It doesn't take but a few strums to learn how the mix of tonewoods, construction and appointments combine to make Taylor's famous playability, intonation and tone. The 300 Series has everything you need and nothing you don't need in a fantastic sounding and playing instrument. The 322 V-Class Grand Concert acoustic ships in a deluxe hardshell case made by Taylor for optimal fit and protection.", price: 1899.00, image_url: "https://media.guitarcenter.com/is/image/MMGS7/L47661000001000-00-720x720.jpg")
Guitar.create(name: "The Loar LH-700 Archtop Acoustic Guitar Vintage Sunburst", description: "The Loar's hand-carved, nitrocellulose-finished LH-700 archtop acoustic guitar is a product of extensive historic research. The all-solid body is finished with nitrocellulose lacquer to reflect the classic jazz sounds of Golden Age instruments. With the use of traditional building techniques like classic parallel bracing, the hand-carved Loar LH-700 is a singular achievement. Its excellent projection and quick decay make it the professional choice for jazz soloing or accompaniment.", price: 1749.99, image_url: "https://media.guitarcenter.com/is/image/MMGS7/581071000015000-00-720x720.jpg")
Guitar.create(name: "Beard Guitars Deco Phonic Sidecar Acoustic Guitar Satin Tobacco Sunburst", description: "The Sidecar from Beard Guitars is the flagship model of the Deco line. The classic and compact Beard “R” body shape is comfortable and appealing, with a solid spruce top featuring mahogany Aero bracing to provide a rich, balanced sound and a slightly pronounced midrange response. The Sidecar is especially suited for fingerstyle and blues. An incredibly subtle soft V-shape mahogany neck and 14 fret range provide plenty of comfort and access.", price: 2200.00, image_url: "https://media.guitarcenter.com/is/image/MMGS7/L84964000001000-00-720x720.jpg")

10.times do
    Order.create(order_number: rand(11111..99999), customer_id: Customer.all.sample.id, guitar_id: Guitar.all.sample.id, purchase_date: Faker::Date.in_date_period)
end

puts "✅ Done seeding!"
